### PR TITLE
Fix POV for Watched Users

### LINKED ISSUE #26: Watched User Info is from the POV of the main user
The watched user data is all based on the viewer / main user of the app. I think this misses the point of "watching" the user. 

PRs Shown:
- Currently: PRs made by the main user are filtered out
- Problem: Watched users may be reviewing a PR made by the main user
- Fix: Filter out PRs based on each watched user so cross review statuses can be seen

Status:
- Currently: The "Waiting" (also "Approved", etc) status means that the _main_ user has yet to review
- Problem: The watched user's PR list should show the status of the PR in relation to the watched user
- Fix: Modify the `OldPullRequest.viewerStatus` to use the watched user as input to filter.

What do you think?

(Note: If these changes are made, the only difference between the "normal" API and the "legacy" API will only be the `isRead` status. It doesn't really work well anyway so maybe we could remove it?)

### PR DESCRIPTION
**Pull request by brevansio**
Addresses #26.

Included a new property in the PullResuests so that we can compare the reviews for a particular person, in this case the same as the query. If functions similarly to how `OldPullRequest`s functioned up until now. Since this requires a new GraphQL query, the `API.swift` file has some newly generated changes.

In addition, I changed the naming and added a fake "isRead" to the `OldPullRequest` by checking if the `currentUser` has made any comments yet.

### CODE REVIEW

File: PRChecker/Shared/Models/OldPullRequest.swift [hunk 1]
```diff
@@ -24,7 +24,16 @@ class OldPullRequest: AbstractPullRequest {
...
+        // There is no `isRead` pre-Github Enterprise 3.0, so we need to fake it
+        guard let nodes = pullRequest.reviews?.nodes else {
+            return false     // No reviews at all
+        }
+        
+        guard let _ = nodes.last(where: { $0?.author?.login.lowercased() == viewingUser.lowercased() }) else {
+            return false     // Viewer has not reviewed
+        }
+        
+        return true
```
Comment (Ckitakishi) [inline PRChecker/Shared/Models/OldPullRequest.swift]: I think `isRead` means "Does the current user read PR already?", and if that is indeed the case, then it probably is not related to `ReviewStatus`. Can we just return a `false` value for pre-Github version?

Comment (brevansio) [reply PRChecker/Shared/Models/OldPullRequest.swift]: Ok, I'll revert that change then.

**Review by Ckitakishi — APPROVED** [review]
LGTM!
